id: AC0C220A9
title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
  the Four Empowerments
type: translation
pechas:
- IA99B625E
- I43000B10
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:40.100045
  last_modified_at: 2023-01-04 12:43:40.100069
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IA99B625E/7E82: B710
  I43000B10/ED96: B710
